name: Test & Lint

on:
  push:
    branches:
      - main
      - release/*
  pull_request:
    branches:
      - main

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

jobs:
  run:
    name: Code linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Node.js 18.x
        uses: actions/setup-node@v3
        with:
          version: 18.x

      - name: npm install
        run: npm install

      - name: Lint
        run: npm run format-check
  selftest:
    name: Self test
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system:
          - ubuntu-latest
          - windows-latest
          - macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Nox (this workflow 😱)
        uses: ./
      - name: Run selftest Noxfile
        run: nox -f selftest.nox.py
